on:
  push:
    branches:
      - master

name: Build and Deploy

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          lfs: true
      - uses: quantargo/action-course-deploy@v1
        with:
          api-key: ${{ secrets.API_KEY }}
